package sketchware.plus.ai;

import android.content.Context;
import android.util.Pair;

import com.besome.sketch.beans.HistoryViewBean;
import com.besome.sketch.beans.ProjectFileBean;
import com.besome.sketch.beans.ViewBean;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import a.a.a.Ox;
import a.a.a.cC;
import a.a.a.eC;
import a.a.a.hC;
import a.a.a.iC;
import a.a.a.jC;
import a.a.a.yq;

import sketchware.plus.managers.inject.InjectRootLayoutManager;
import sketchware.plus.tools.ViewBeanParser;

public class SketchwareXmlBridge {

    /**
     * Converts current Sketchware ViewBeans into standard Android Studio-style XML
     * for the AI to read and understand, while protecting the root layout attributes.
     */
    public static String convertToAndroidStudioXml(Context context, String scId, ProjectFileBean projectFile) {
        String rawXml = getRawXml(context, scId, projectFile);
        if (rawXml.startsWith("<!-- Error")) return rawXml;
        
        // Protect the root: Remove namespaces and internal boilerplate from the root tag
        // to prevent AI from getting confused or trying to modify system-managed parts.
        return prepareXmlForAi(scId, projectFile.getXmlName(), rawXml);
    }

    /**
     * Generates the raw XML for the project file, exactly as the "Direct XML Editor" would show it.
     */
    public static String getRawXml(Context context, String scId, ProjectFileBean projectFile) {
        try {
            eC dataManager = jC.a(scId);
            hC fileManager = jC.b(scId);
            iC libraryManager = jC.c(scId);

            yq workspace = new yq(context, scId);
            workspace.a(libraryManager, fileManager, dataManager);
            
            // Force g to false to ensure NO activity decor injection happens.
            // In DesignActivity's editor mode, buildConfig.g is often false or ignored by Ox
            // when excludeAppCompat is true, but forcing it here ensures consistency.
            workspace.N.g = false;

            String xmlName = projectFile.getXmlName();
            ArrayList<ViewBean> viewBeans = dataManager.d(xmlName);
            ViewBean viewFab = dataManager.h(xmlName);

            // Use Sketchware's Ox engine to generate raw XML
            Ox ox = new Ox(workspace.N, projectFile);
            ox.setExcludeAppCompat(true);
            // eC.a filters only root-level views, preventing internal system views from leaking.
            ox.a(eC.a(viewBeans), viewFab);

            return ox.b();
        } catch (Exception e) {
            e.printStackTrace();
            return "<!-- Error generating raw XML: " + e.getMessage() + " -->";
        }
    }

    /**
     * Takes standard XML generated by the AI, parses it into Sketchware's ViewBean structure,
     * updates the project state, and saves it to disk.
     */
    public static boolean applyAiXmlToSketchware(Context context, String scId, String xmlName, String aiXml) throws Exception {
        // 1. Clean markdown or chatter from AI response
        String sanitizedXml = sanitizeAiXmlInput(aiXml);

        // 2. Wrap AI's children back into the ORIGINAL root layout to ensure stability
        String stableXml = reRootWithOriginalConfig(scId, xmlName, sanitizedXml);

        // 3. Parse XML into Sketchware ViewBeans
        ViewBeanParser parser = new ViewBeanParser(stableXml);
        parser.setSkipRoot(true);

        ArrayList<ViewBean> newBeans = parser.parse();

        if (newBeans == null) {
            throw new IllegalArgumentException("Failed to parse AI XML into valid ViewBeans.");
        }

        // 4. Update Root Layout attributes (mirrors ViewCodeEditorActivity)
        Pair<String, Map<String, String>> root = parser.getRootAttributes();
        InjectRootLayoutManager rootLayoutManager = new InjectRootLayoutManager(scId);
        rootLayoutManager.set(xmlName, InjectRootLayoutManager.toRoot(root));

        // 5. Update Sketchware Memory and History (mirrors ViewCodeEditorActivity)
        eC dataManager = jC.a(scId);
        ArrayList<ViewBean> oldBeans = dataManager.d(xmlName);

        HistoryViewBean historyBean = new HistoryViewBean();
        historyBean.actionOverride(newBeans, oldBeans);

        cC historyManager = cC.c(scId);
        if (!historyManager.c.containsKey(xmlName)) {
            historyManager.e(xmlName);
        }
        historyManager.a(xmlName);
        historyManager.a(xmlName, historyBean);

        // Update the view beans list for this XML file in memory
        dataManager.c.put(xmlName, newBeans);

        // 6. Save changes to Sketchware project files on storage
        yq workspace = new yq(context, scId);
        dataManager.n(workspace.projectMyscPath + "view");

        return true;
    }

    /**
     * Strips proprietary or unnecessary headers so the AI gets clean XML.
     * Also protects the root layout by simplification.
     */
    private static String prepareXmlForAi(String scId, String xmlName, String rawXml) {
        if (rawXml == null) return "";
        
        InjectRootLayoutManager rootManager = new InjectRootLayoutManager(scId);
        InjectRootLayoutManager.Root root = rootManager.getLayoutByFileName(xmlName);
        
        String children = extractChildren(rawXml);
        
        StringBuilder sb = new StringBuilder();
        sb.append("<!-- ACTIVITY ROOT: ").append(root.getClassName()).append(" -->\n");
        sb.append("<!-- You can change this root type or add containers inside it -->\n");
        sb.append("<").append(root.getClassName());
        
        // Provide only necessary context attributes
        Map<String, String> attrs = root.getAttributes();
        if (attrs.containsKey("android:orientation")) {
            sb.append(" android:orientation=\"").append(attrs.get("android:orientation")).append("\"");
        }
        
        if (children.isEmpty()) {
            sb.append(" />");
        } else {
            sb.append(">\n");
            sb.append("    <!-- ADD OR MODIFY VIEWS INSIDE HERE -->\n");
            sb.append(children);
            sb.append("\n</").append(root.getClassName()).append(">");
        }
        
        return sb.toString().trim();
    }

    private static String extractChildren(String xml) {
        int firstStart = xml.indexOf("<");
        if (firstStart == -1) return "";
        
        int firstEnd = xml.indexOf(">", firstStart);
        if (firstEnd == -1) return "";
        
        // Check if self-closing
        if (xml.substring(firstStart, firstEnd + 1).endsWith("/>")) return "";
        
        int lastStart = xml.lastIndexOf("</");
        if (lastStart > firstEnd) {
            return xml.substring(firstEnd + 1, lastStart).trim();
        }
        return "";
    }

    public static String reRootWithOriginalConfig(String scId, String xmlName, String aiXml) {
        InjectRootLayoutManager rootManager = new InjectRootLayoutManager(scId);
        InjectRootLayoutManager.Root originalRoot = rootManager.getLayoutByFileName(xmlName);
        
        String trimmedAiXml = aiXml.trim();
        
        // Extract the root tag name from AI's XML
        String aiRootTag = null;
        Pattern p = Pattern.compile("^<([\\w\\.]+)", Pattern.MULTILINE);
        Matcher m = p.matcher(trimmedAiXml);
        if (m.find()) {
            aiRootTag = m.group(1);
        }

        String innerContent;
        String finalRootClass = originalRoot.getClassName();
        Map<String, String> finalAttrs = new LinkedHashMap<>(originalRoot.getAttributes());

        // If the AI provided a root that matches our current class, or if it's a known layout,
        // we extract children. Otherwise, we treat the whole thing as content.
        if (aiRootTag != null && (aiRootTag.equals(originalRoot.getClassName()) || aiRootTag.contains("Layout") || aiRootTag.contains("View"))) {
            innerContent = extractChildren(trimmedAiXml);
            if (innerContent.isEmpty() && !trimmedAiXml.contains("</")) {
                innerContent = trimmedAiXml;
            } else {
                // The AI provided a root, let's see if we should adopt its attributes/class
                finalRootClass = aiRootTag;
                // Try to extract attributes from the AI root tag
                int firstEnd = trimmedAiXml.indexOf(">");
                if (firstEnd != -1) {
                    String rootOpenTag = trimmedAiXml.substring(0, firstEnd);
                    Pattern attrPattern = Pattern.compile("(\\w+:\\w+)=\"([^\"]*)\"");
                    Matcher attrMatcher = attrPattern.matcher(rootOpenTag);
                    while (attrMatcher.find()) {
                        finalAttrs.put(attrMatcher.group(1), attrMatcher.group(2));
                    }
                }
            }
        } else {
            innerContent = trimmedAiXml;
        }
        
        // Update the system root configuration
        rootManager.set(xmlName, new InjectRootLayoutManager.Root(finalRootClass, finalAttrs));

        StringBuilder sb = new StringBuilder();
        sb.append("<").append(finalRootClass).append(" ");
        sb.append("xmlns:android=\"http://schemas.android.com/apk/res/android\" ");
        sb.append("xmlns:app=\"http://schemas.android.com/apk/res-auto\" ");
        sb.append("xmlns:tools=\"http://schemas.android.com/tools\" ");
        
        for (Map.Entry<String, String> entry : finalAttrs.entrySet()) {
            if (!entry.getKey().startsWith("xmlns:")) {
                sb.append(entry.getKey()).append("=\"").append(entry.getValue()).append("\" ");
            }
        }
        
        sb.append(">\n").append(innerContent).append("\n</").append(finalRootClass).append(">");
        return sb.toString();
    }

    /**
     * Extracts pure XML from AI responses (handles ```xml block wrappers or conversational prefix text).
     */
    public static String sanitizeAiXmlInput(String aiResponse) {
        if (aiResponse == null) return "";

        String trimmed = aiResponse.trim();

        // Check for markdown code blocks
        if (trimmed.contains("```")) {
            Pattern pattern = Pattern.compile("```(?:xml)?\\s*([\\s\\S]*?)\\s*```", Pattern.CASE_INSENSITIVE);
            Matcher matcher = pattern.matcher(trimmed);
            if (matcher.find()) {
                return matcher.group(1).trim();
            }
        }

        // Fallback: extract from first '<' to last '>'
        int start = trimmed.indexOf("<");
        int end = trimmed.lastIndexOf(">");
        if (start != -1 && end > start) {
            return trimmed.substring(start, end + 1).trim();
        }

        return trimmed;
    }
}